# Generated by Django 4.2.17 on 2024-12-29 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='nsfw_filter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
